### ISSUE TITLE
Nier Automata

### ISSUE THREAD

**Issue by Skykila** [Kerilk/noesis_bayonetta_pc#1]
Do you plan to support animation from Nier Automata?

**Comment by Kerilk** [comment]
The (long term) goal would be to support PG games that use this engine (dmc, Transformers: Devastation, Nier Automata, Vanquish, etc...). But I don't own all of those yet so it may take some time.

**Comment by Kerilk** [comment]
Animation support for Nier Automata has been released.

https://github.com/Kerilk/noesis_bayonetta_pc/releases/tag/0.9.16
