### ISSUE TITLE
-Scale option not apladed to animation export

### ISSUE THREAD

**Issue by Skykila** [Kerilk/noesis_bayonetta_pc#10]
Аnimation is exported with a scale of 1.0 (as opposed to models). Option "-Scale" Ignored.

**Comment by Kerilk** [comment]
This problem is a Noesis issue. The exporter is not part of the plugin.

**Comment by Skykila** [comment]
So, maybe you could scale (e.g. scale 100) the imported model?

**Comment by Kerilk** [comment]
Why would I want to change the scale? Bayonetta models are in meters. If you want to change the scale, either do it on export (Noesis responsibility, seems to need fixing, thus report the bug to Rich) or on import, all major editing software allow changing unit on import.

**Comment by Skykila** [comment]
> Why would I want to change the scale? 

Animation problem. MotionBuilder don't allow changing unit on import.
