### ISSUE TITLE
extract nca

### ISSUE THREAD

**Issue by redtankbai** [Kerilk/noesis_bayonetta_pc#12]
i know it's not relative your pluggin, but im kinds of stucked on extract nca file of Astral Chain, just like to know if you have idea about it
basically i can get nca files from XCI and that's it, cannot extract nca file, tool says i need to get title keys for the game, but no idea where to get keys

any point?

**Comment by Skykila** [comment]
try this 
https://github.com/bodyXY/Ultimate-Material-Hactool-GUI/releases

**Comment by redtankbai** [comment]
tried that gui tool, it still request title keys when extract nca files, so same issue
where you find title keys for this game? i digged in google and nothing really help

**Comment by Skykila** [comment]
use XCI-Explorer, it download keys.txt 
https://github.com/StudentBlake/XCI-Explorer/releases

**Comment by redtankbai** [comment]
thx for follow up, i try xci explorer as well, it do get a key txt, but none of the key in side helps, also tried re-extract xci with new key txt, nothing different.
i tried extract nsp file which people said can get tik files there for title key, but no tik comes out, only nac and a xml file.
do you get content with no peoblem? could you just share them? because i only interested in their char and monster pkz files
i see people share some of them, but only main character, still want others
thx!

**Comment by Skykila** [comment]
Use keys.txt in Ultimate Material Hactool GUI, 
![image](https://user-images.githubusercontent.com/6079712/64127939-eb829b00-cdc4-11e9-9a22-659f4bbe94c6.png)

**Comment by redtankbai** [comment]
oh dear... leave it empty...
it works now, thank you!
