### ISSUE TITLE
Transformers: Devastation

### ISSUE THREAD

**Issue by Demonslayerx8** [Kerilk/noesis_bayonetta_pc#13]
Issue loading up models from this game. [Issue reported to me by @Akuago220 via twitter]
![image](https://user-images.githubusercontent.com/17195757/64144889-63ec5a80-cdcb-11e9-8f52-d89ffbb9a844.png)

Here's the file that he gave me.
https://www.mediafire.com/file/agsafa5bsdztu8r/Menasor_files.zip/file
![image](https://user-images.githubusercontent.com/17195757/64144956-a01fbb00-cdcb-11e9-9832-26af2ae401d3.png)

**Comment by Kerilk** [comment]
There is no support yet for Transformer Devastation, it is on the todo list. were you able to load any TD file using the plugin?

**Comment by Demonslayerx8** [comment]
He wasn't able to open any TD files at all with the plugin.

**Comment by Kerilk** [comment]
Progress: https://github.com/Kerilk/bayonetta_tools/commit/48e651458809c40f0454170205b4a36de608cf72

**Comment by Kerilk** [comment]
https://github.com/Kerilk/noesis_bayonetta_pc/tree/v0.9.29

Materials are not correctly supported, but the rest should be working.

![TD](https://user-images.githubusercontent.com/1815142/64402091-40c6e280-d039-11e9-8d52-86624d196dcf.png)

**Comment by Demonslayerx8** [comment]
Alright, I'll have Akuago test it.

Edit:
Works just fine for him, he sends his thanks.

**Comment by Kerilk** [comment]
Perfect
