### ISSUE TITLE
Astral Chain Emissive Meshes not loading/exporting

### ISSUE THREAD

**Issue by Deschamps12** [Kerilk/noesis_bayonetta_pc#15]
Hey! Amazing with work with the plugin,
I found that when exporting maps, meshes with emissive properties don't seem to load in on Noesis or on export (specifically on maps). 
For example:
[ST1: r124.dat]
ingame:
![image](https://user-images.githubusercontent.com/57378717/76862941-ce775c00-682c-11ea-9fa7-aef43ba28ae5.png)

emissive part not loaded into noesis, 
![image](https://user-images.githubusercontent.com/57378717/76862821-a4259e80-682c-11ea-83ac-c25789c7765e.png)
not there on export:
![image](https://user-images.githubusercontent.com/57378717/76864301-de903b00-682e-11ea-9580-8819b0df0ad3.png)

**Comment by Kerilk** [comment]
I only got sample files for this game so I would need this one to investigate.

**Comment by Deschamps12** [comment]
> I only got sample files for this game so I would need this one to investigate.

sure! if you need any other files let me know and I can provide

**Comment by Kerilk** [comment]
Aren't those emmissive parts in the r124_props.txt?
You have:
object:x,y,z;rx,ry;rz;sx,sy,sz
meaning position, rotation and scaling

Also apparently the plugin crashes when I try to load the textures, maybe the whole uncompressed thing is more than 4GB.

**Comment by Deschamps12** [comment]
> Aren't those emmissive parts in the r124_props.txt?
> You have:
> object:x,y,z;rx,ry;rz;sx,sy,sz
> meaning position, rotation and scaling
> 
> Also apparently the plugin crashes when I try to load the textures, maybe the whole uncompressed thing is more than 4GB.

nah, that file is exactly that, but the third picture was taken with all props already placed.
The emissive parts are not props sadly but part of the map themselves. I had thought that at first but I’ve gone through all the props and nothing, also there’s some more obvious chunks like part of the ceiling of the tunnels that theres no way could be something else. 

And yeahhh sadly for maps and other big props I have to use the previous version of the plugin that doesn’t load the textures and then just export all the textures manually with switch toolbox.  It’s a pain but works lol. but yeah, the older untextured version should work

When exporting the mesh this comes up, I’m guessing this might have something to do with it 
![C847A776-4C2E-41CB-AC95-A56E97310935](https://user-images.githubusercontent.com/57378717/77144451-f1d02000-6a53-11ea-9ffe-0093118c03e7.png)

**Comment by Kerilk** [comment]
You can also rename the texture file, this way the plug-in can't find it. I'll investigate more.

**Comment by Deschamps12** [comment]
> You can also rename the texture file, this way the plug-in can't find it. I'll investigate more.

That works too, and actually by doing that the missing meshes load in on the latest version! It looks like everything is there so far but I'll test it out some more after work

**Comment by Kerilk** [comment]
Ho you must have had a version where I was missing some vertex types. I'll still look at it to check that there isn't a new type inside. And maybe also add support so that you get all the UVs on export.

**Comment by Kerilk** [comment]
Fixed: https://github.com/Kerilk/noesis_bayonetta_pc/releases/tag/v0.9.34. I was still missing one vertex format. And some textures were not decoded correctly. Tell me if you get more warnings on other files.
![Astral Chain Level](https://user-images.githubusercontent.com/1815142/77217408-4628dd80-6af0-11ea-98d4-4b6b7ac4f906.png)

**Comment by Kerilk** [comment]
Are you still experiencing issues or can I close this one?

**Comment by Deschamps12** [comment]
Sorry, been out of town and havent been able to check, ill check more tomorrow though!

**Comment by Deschamps12** [comment]
So mostly everything seems fine, 
some props and stages give this error 
![image](https://user-images.githubusercontent.com/57378717/78178734-b9eab480-7425-11ea-8746-3e121aff6615.png)
For example: ba0033.dat, ba9e00.dat. ba1101.dat, r124.dat
not sure how relevant it is, exports seem fine to me

there's also another thing but I'm not exactly sure if its shader shenanigans or what
I don't get any errors on export but all the holographic things (like signs, holo mannequins, etc) uvs are really weird. 
None match the textures for the models
I was thinking it was due to shaders but i cant rlly think of how they'd match being the way they are 
example: bg6400
![image](https://user-images.githubusercontent.com/57378717/78184733-93317b80-742f-11ea-8999-16a79e98c51a.png)
![image](https://user-images.githubusercontent.com/57378717/78184744-988ec600-742f-11ea-97a4-773076ceb23c.png)
2nd is the Uvs that come out.
I'm thinking that the first UV layer is for the glitching texture that is overlayed on top but i think there should be a second UV layer for the actual texture of the mannequin/object itself 
same thing with signs 
![image](https://user-images.githubusercontent.com/57378717/78185674-0c7d9e00-7431-11ea-94e0-7e376a3f4185.png)
(bg1045.dat)

**Comment by Kerilk** [comment]
Thanks for the detailed report. Glad to see things are mostly fine.
Normally I report all UVs to noesis, but from Noesis ReadMe.txt:
```
- Support for an arbitrary number of UV channels in the rpg interface. The preview renderer only uses UV0/UV1, but additional channels can be viewed in the data viewer and are passed through to exporters. I've only updated the FBX (2019) and glTF exporters to support additional channels.
```
So as you use the FBX exporter you should be able to switch to the correct UV. The UV channel used may very well be shader based and thus a shader database would need to be built to correctly support everything. Same for multi-texturing where the color value dictates the ratios of textures to blend.

I will close this issue, don't hesitate to open a new one if you feel the need.
Thanks again for the report.
