### ISSUE TITLE
Nier Automata Animation Loading

### ISSUE THREAD

**Issue by TokuNiArimasen** [Kerilk/noesis_bayonetta_pc#16]
Hi, kind of new to using Noesis and your plugin. I'm having trouble loading the animations for the 2B model from Nier Automata, using your plugin. I try to open pl0000.dtt, and then when it asks me to load the motion files, I select pl0000.dat, but it keeps asking me to select the motion file. When I click cancel, the model appears in Noesis, but I'm not sure if the animations are loaded. I cancel disable the armor meshes in the Data Viewer to see 2B clearly, but I don't know where to look to see if the animations are loaded in. Any ideas on what to do?
![loop](https://user-images.githubusercontent.com/60960234/77238227-b20c5400-6b8b-11ea-8039-10f382a1a97a.jpg)
![loop2](https://user-images.githubusercontent.com/60960234/77238228-b2a4ea80-6b8b-11ea-995f-f790c23fdfe1.jpg)
![loop3](https://user-images.githubusercontent.com/60960234/77238229-b33d8100-6b8b-11ea-9e88-56480239b5ea.jpg)

**Comment by Kerilk** [comment]
Animations are in pl000f.dat

be careful though: https://github.com/Kerilk/noesis_bayonetta_pc/issues/5

**Comment by TokuNiArimasen** [comment]
> 
> 
> Animations are in pl000f.dat
> 
> be careful though: #5

Ahhh, gotcha. Thanks a lot, and thanks for the heads up, too! Great work!
