### ISSUE TITLE
Recent version crashes upon opening Star Fox Zero .dat files.

### ISSUE THREAD

**Issue by Akuago220** [Kerilk/noesis_bayonetta_pc#17]
[ncr3213.txt](https://github.com/Kerilk/noesis_bayonetta_pc/files/4399640/ncr3213.txt)

As the title says, any time I open .dat files from Star Fox Zero with the v0.9.34 Previous version does open the .dat files, though it does not show the textures as the preview picture did.

![image](https://user-images.githubusercontent.com/57743939/77858882-371eeb00-71d4-11ea-897b-86c2c4ae24cd.png)

![image](https://user-images.githubusercontent.com/57743939/77858524-28373900-71d2-11ea-917f-ed53cbb5a94e.png)

Link to test files used: https://www.mediafire.com/file/z0g4ydf1qygkov1/Andross_Zero_Set.zip/file

**Comment by Kerilk** [comment]
I cant reproduce.
Couples of things to check:
 - Update Noesis to the most recent version
 - Check that there is no bayonetta.dll in the plugin floder
 - Check that `TexConv2.exe`, `texUtils.dll` and `gfd.dll` are in Noesis' directory (can be found [here](https://github.com/NWPlayer123/WiiUTools/tree/master/TexHaxU))
This is what I get using latest version:
![image](https://user-images.githubusercontent.com/1815142/77863424-eca76980-71e7-11ea-933c-574f005cbfee.png)
![image](https://user-images.githubusercontent.com/1815142/77863537-d2ba5680-71e8-11ea-825c-fb4f5560cb9c.png)
