### ISSUE TITLE
put animation into different files

### ISSUE THREAD

**Issue by redtankbai** [Kerilk/noesis_bayonetta_pc#2]
hi,

first of all, thx for made this amazing plugin!

i want to know, is that possible to export animation sequence into different files instead of in one big file?

thanks!

**Comment by Kerilk** [comment]
Thanks for the kind comment. You can export animation in several files using:
.noefbxmulti
as an export format for animations and you should get one animation per file, properly named.

**Comment by redtankbai** [comment]
It works, many thanks!

**Comment by Galetron** [comment]
I tried doing this for Raiden's animations from MGR:R, and just got the bones, and no character model, i did some tests, and i can't seem to combine the model and rig easily, so im at a loss on what to do here to make the separate animations playable, and this leaves me stuck at a major road block to my goal.
