### ISSUE TITLE
The Wonderful 101

### ISSUE THREAD

**Issue by platinumT** [Kerilk/noesis_bayonetta_pc#20]
First of all, thank you so SO MUCH for all the work you've done on the platinum games. I'm a really big fan of their productions and being able to study their assets is invaluable to me, I learnt a lot thanks to your plugin. 

I'm looking into the wonderful 101 assets right now and models seem to work perfectly, at least all the models in the pl folder that I've tested seem to load fine. 
However contrary to other games in which there were some dtt files next to the .dat, the pl folder only contains the .dat files. The textures seem to be stored in a big pl_texture.wtb file and as such the plugin doesn't grab them.

Also I didn't manage to find the animations, I tried all the "traditionnal" files like pl000f.dat etc but that didn't work.

So if you have the time I'd really appreciate if you could look into that game. No rush at all and once again thanks a ton for all you do ! Take care !

**Comment by Kerilk** [comment]
Thanks for the kind comment. At least it doesn't seem to crash Noesis.

**Comment by Kerilk** [comment]
Okay i have added support for this game. Textures are still a mess as some files are shared between models and, without building a database of texture ids, there is no way to know where.

Motions are in plf003.dat, plf004.dat, etc... you need to change the prefix accordingly.

**Comment by platinumT** [comment]
Thank you so much !
