### ISSUE TITLE
Support for MadWorld

### ISSUE THREAD

**Issue by 564498dfs** [Kerilk/noesis_bayonetta_pc#21]
Wasn't sure where to post about this, I asked on Xentax and was told that MadWorld is a Platinum Games game https://forum.xentax.com/viewtopic.php?f=16&t=22539 and the samples I submitted seems to be the same as the other games.
http://www.mediafire.com/file/3mm0r5akfe42gxx/pl.zip/file

Cheers.

**Comment by Kerilk** [comment]
Thanks for bringing this one to my attention. Some of the formats are unknown to me (model, texture container), while other are already supported (animations). I'll see what I can do, but no promises and no ETA.

**Comment by platinumT** [comment]
Thank you for your hard work Kerilk ! 
It looks like the Noesis g1m plugin author already made some good progress on the model format, this is promising.

**Comment by Joschuka** [comment]
The model format is now mostly figured out : https://forum.xentax.com/viewtopic.php?f=16&p=165877#p165877
Normals and UVs are missing, I'm a bit confused about how they work. I don't think I'll work on the textures since I don't like that, I'm mostly interested in the animations for that game.

**Comment by Kerilk** [comment]
I released a new version with support for MadWorld, tell me how it goes.

**Comment by platinumT** [comment]
Working perfectly for all the enemies I tested so far, awesome job !

**Comment by Kerilk** [comment]
I released a new version fixing a couple of issues with CMPR(BC1) texture decoding, and some scrambled models due to missing normals.

**Comment by 564498dfs** [comment]
For the files in Case0 - Case5 , CaseA - CaseF don't open and cannot be exported

**Comment by Joschuka** [comment]
Looking good to me, at least on all the models I checked. Thank you for supporting the game !

**Comment by Kerilk** [comment]
I added support for the levels. I also changed the default material behavior as the game favors transparency above other usage of the alpha channel. I also disabled lighting for materials as the engine did not support dynamic lighting, from the screen shots I could see.
