### ISSUE TITLE
Anarchy Reigns mesh and texture issues

### ISSUE THREAD

**Issue by 564498dfs** [Kerilk/noesis_bayonetta_pc#22]
As stated from https://forum.xentax.com/viewtopic.php?f=16&t=9142 "I'm having the same issue as the first post, Including missing meshes and texture issues. Example file: http://www.mediafire.com/file/p4o1md1bkrsz442/Jack.zip/file" 
![JackCayman](https://user-images.githubusercontent.com/61811748/90984420-d3121000-e542-11ea-971d-fba5149b6d1b.PNG)

**Comment by Kerilk** [comment]
Anarchy Reigns is a little tricky to use.

For hi-res texture you need:
- To have unpacked the whole data000.cpk somewhere
- load the base version of a model: here pl2050.dat
- load a color variation of the model when prompted, here, for example pl2051.dat
![image](https://user-images.githubusercontent.com/1815142/90984792-018cec80-e53d-11ea-94e4-974505613917.png)
For pl2050 you have 8 color variation in pl2051 to pl2059.

As far as the left arm is concerned it is in another model, you can confirm it by opening the model using the binary templates of bayonetta_tools:
![image](https://user-images.githubusercontent.com/1815142/90984838-60526600-e53d-11ea-88b5-740ca57d55a4.png)
There is only a `Rarm` mesh, the left arm is somewhere else.

**Comment by Kerilk** [comment]
wp1050 seems like a good bet for the left arm, but I have never played the game. I don't know where the texture is for this one, most probably in pl1050 or pl1051. They should be exported with the main model.

**Comment by 564498dfs** [comment]
![arm](https://user-images.githubusercontent.com/61811748/90985216-85000b00-e548-11ea-9f2a-3d32d9916b3f.PNG)
Yep it's his arm, I loaded pl2050 - pl2055 and it got it, Cheers I'll make note of this

**Comment by Kerilk** [comment]
Glad you got it to work, I can't manage to get it textured. I you could describe precisely how you did it I am curious.

**Comment by 564498dfs** [comment]
Oops I made a typo my apologies, I actually loaded pl1050 - pl1057 then the texures loaded

**Comment by 564498dfs** [comment]
I looked at it again and it seems the only one that loads is pl1050 for textures

**Comment by GBOATET** [comment]
I've been trying forever but can't find a way to extract character's missing parts.

I only know how to get DATs form Anarchy Reigns' 360 version, not WBTs or WMBs, even though that's the only way to find stuff with the binary templates. Which I don't even know how to use those.

Can I get some help? No one has anything else online and it's frustrating that I find extracted models but no explanations or clarification...

**Comment by Kerilk** [comment]
The missing part are just in different dat files. You need to look for them using noesis. See the example above for pl2050.dat and its arm pl1050.dat. Noesis should be exporting both of those fine.
