### ISSUE TITLE
Nova Prime from Transformers Devastation

### ISSUE THREAD

**Issue by Akuago220** [Kerilk/noesis_bayonetta_pc#24]
Less of an issue, more of an inquiry.

Just wanted to see if Nova Prime had a functional rig to his file. He was in pre-rendered cutscenes so I was surprised to see his files in here. If not, that's fine, I can get someone else to rig him for a price.

![image](https://user-images.githubusercontent.com/57743939/101442157-b1b61380-38e8-11eb-80df-55d9617b311b.png)

[Nova Prime Set.zip](https://github.com/Kerilk/noesis_bayonetta_pc/files/5656970/Nova.Prime.Set.zip)

**Comment by Kerilk** [comment]
Unfortunately the model is not rigged:
![image](https://user-images.githubusercontent.com/1815142/104107186-0a7a2280-5280-11eb-86e4-f5872fbd2a35.png)
