### ISSUE TITLE
Texture Keep asking Load Shared texture Anarchy reign PS3

### ISSUE THREAD

**Issue by BlueWaver** [Kerilk/noesis_bayonetta_pc#25]
I have a problem with Anarchy reign ps 3 where the plugin keep asking to "Load the shared Textures in other files?" even after I load like the previous Issue do it still asking like selecting the file pl00b0.dat and then select pl00b1.dat but after that it still asking the same question and after I cancel it it just show "the file can't be reviewed, but may exported"

**Comment by Kerilk** [comment]
The PS3 version isn't supported, I don't know how to read the textures. If you make a sample available to me I may be able to do something.

**Comment by BlueWaver** [comment]
Ok Thank you for your Hard work =w=7
