### ISSUE TITLE
NieR Replicant support?

### ISSUE THREAD

**Issue by redtankbai** [Kerilk/noesis_bayonetta_pc#26]
Hi Kerilk,

https://forum.xentax.com/viewtopic.php?f=10&t=23783#p173695

there is a unpacker for NieR Replicant already, will you have a look on this game?

thanks!

**Comment by Kerilk** [comment]
Hello, @WoefulWolf is looking at reversing the game. It is not base on a Platinum engine, so I doubt I will add support for it in the plugin. We'll see.

**Comment by redtankbai** [comment]
thx for reply
