### ISSUE TITLE
 may I ask how to use this plug-in?

### ISSUE THREAD

**Issue by Li-ZhuoHang** [Kerilk/noesis_bayonetta_pc#29]
Excuse me, may I ask how to use this plug-in? I only have source code after downloading, but no dll.

**Comment by Kerilk** [comment]
There is a release tab on the main page the DLLs are there, compressed.
https://github.com/Kerilk/noesis_bayonetta_pc/releases

**Comment by Li-ZhuoHang** [comment]
Oh, I found it, thank you very much, I can now unpack Bayonetta's CPK, but how to open the dat ?

**Comment by Kerilk** [comment]
Usually double click should work, be sure noesis is up to date

**Comment by Li-ZhuoHang** [comment]
Ok, but there is only model, and there is no action, how should I extract the action?

**Comment by Kerilk** [comment]
Activate the motion prompt in the tools/Bayonetta menu (put a 1), reload the model.
What game file are you loading?

**Comment by Li-ZhuoHang** [comment]
I am loading Bayonetta pl0000.dat and I turned on animation Prompt, when I click pl0000.dat it will show load Motions for PL0000 in other files

**Comment by Kerilk** [comment]
Load pl0010.dat when prompted and then cancel

**Comment by Li-ZhuoHang** [comment]
Ok, but this seems to only have the model, where is the action file?

**Comment by Kerilk** [comment]
Did you load pl0000.dat, and when prompted load pl0010.dat?

**Comment by Li-ZhuoHang** [comment]
when I click pl0000.dat it will show load Motions for pL0000 in other files

**Comment by Li-ZhuoHang** [comment]
I don't quite understand how to operate to show the action

**Comment by Li-ZhuoHang** [comment]
Could you tell me the steps of extracting the animation?

**Comment by Li-ZhuoHang** [comment]
When I double-click pl0000.dat, I select pl0010.dat, but there is still no animation, or when I double-click pl0010.dat, I select pl0000.dat

**Comment by Li-ZhuoHang** [comment]
I found that only the player's model doesn't have animation, some other items directly double-click dat to show the action

**Comment by Kerilk** [comment]
You need to double click on pl000.dat, when pompted leave pl0010 in the box, click OK select pl0010.dat, click open and then click cancel until you see the model.

**Comment by Li-ZhuoHang** [comment]
I tried following the steps you said, but I still could only see the model without animation

**Comment by Kerilk** [comment]
Well, are you sure your file comes from bayonetta and not bayonetta 2?
If it were the case load pl000f.dat when pompted leave pl000f in the box, click OK select pl001f.dat, click open and then click cancel until you see the model.

**Comment by Li-ZhuoHang** [comment]
Oh, sorry, I extracted Bayonetta2, is there any difference between Bayonetta2 and Bayonetta operation?

**Comment by Li-ZhuoHang** [comment]
Thank you very much for your reply. I have successfully extracted the animation

**Comment by Li-ZhuoHang** [comment]
Could I ask you one more question? please

**Comment by Kerilk** [comment]
Sure, shoot.

**Comment by Li-ZhuoHang** [comment]
Thank you.Do you know where the animation files for 2A are? I only found her model.

**Comment by Kerilk** [comment]
2A? what model is that?

**Comment by Li-ZhuoHang** [comment]
For the characters that players can operate in Nier: automata, I can now find the animation of 9s and 2B, but I can't find the animation of 2A

**Comment by Kerilk** [comment]
I am unsure A2 has a different set of animations from 2B.

**Comment by Li-ZhuoHang** [comment]
Do you mean that the a2 animation and 2b animation files are the same?
Now I want to find some a2 animations, I don't know which file should I choose

**Comment by Kerilk** [comment]
Yes I think A2 and 2B animations are the same.

**Comment by Li-ZhuoHang** [comment]
OK,Could you tell me which file it is?

**Comment by Kerilk** [comment]
You need to change the prefix to fit B2's one and then load the file containing B2's animations. That's what the text box is for.

**Comment by Li-ZhuoHang** [comment]
I want to find A2 animation. Could you tell me how I do it? I know how to extract the animation of 2B,but I can't find the animation file of A2

**Comment by Kerilk** [comment]
A2 does not have dedicated animations, it reuses 2B animations they have the same skeleton, (except for cloth bones that are not animated this way anyway.) Just reapply 2B animations to A2. You can do that with the plugin by loading the A2 model, when prompted change the prefix to the same as 2B then click OK, load 2B animation file and you should be good.

**Comment by Li-ZhuoHang** [comment]
Why can't I load it? My action is: double click pl010.dat(in data100_Files)→ select PI000F.dat in Data006_Files in Load Motion.
So strange....

**Comment by Kerilk** [comment]
Because you didn't read what I wrote and did not type pl0000 in the text box before selecting pl000f.dat

On a side note, if you want all the anims you need to use the 64 bit version of noesis, as the 32 bit one does not allow all anims to be loaded before running out of memory.

**Comment by Li-ZhuoHang** [comment]
Sorry, because my English is not very good, so it is a little difficult to understand... I misunderstand what you mean
Fortunately, I can now display a2 animation, thank you very much for your guidance.

**Comment by Kerilk** [comment]
Glad you got that working.

**Comment by Li-ZhuoHang** [comment]
Do you know how Ninja Gaiden 3 Razor's edge extracts animation? As far as I know, the file type of this game after unpacking is also dat.

**Comment by Kerilk** [comment]
The animation format I support is proprietary to Platinum Games so, if it is not a platinum game, I wouldn't know.
