### ISSUE TITLE
cannot load animation from pl000f.dat

### ISSUE THREAD

**Issue by redtankbai** [Kerilk/noesis_bayonetta_pc#3]
hi again,

i'm trying to get main character animation of bayonetta 2, after extract dat files, i found they are in pl000f.dat, but when i use your neosis plug-in to load this file, it seems cannot load animation with. i also tried reassign motion file in the dialog, but not working.

have and idea about this issue?
thanks!

**Comment by Kerilk** [comment]
No, they are in pl001f.dat file and prefix is pl000f for bayo 2 or pl0010 for bayo 1 motions.

**Comment by redtankbai** [comment]
ok... when i try open pl001f.dat, it says "File could not be previewed", and says "The file type could not be determined" when i export it
and no animation been loaded if i open pl000f.dat with prefix pl001f
im working on bayo 2, so any idea?

**Comment by Kerilk** [comment]
No, you open pl0000.dat (it contains the model) and use prefix pl000f on pl001f.dat (it contains the animations). pl000f.dat is the enemy bayonetta 2 model.

**Comment by redtankbai** [comment]
oh, it works after couple try, i have to say the ui is a bit confusing
anyway, thanks a lot
