### ISSUE TITLE
Nier Automata Animations Wont Export (64Bit)

### ISSUE THREAD

**Issue by keesoudwater34** [Kerilk/noesis_bayonetta_pc#30]
Using the new 64 bit version of noesis was able to do the animations of the HO229 Flight Unit. But as soon as im attempting on 2B it gets stuck and never exports anything. Left it overnight the other day and still didnt spit nothing out.  ill be attempting 9s in a second am hoping that does work. am also exporting to psk and psa due to the workflow for proccessing them afterwards. 

don't know if im the only one experiencing that issue. also it seems to be it also warns about multiple root bones but the HO229 had that too and that exported fine so im a bit confused whats going wrong with the export

**Comment by Kerilk** [comment]
Thanks for reporting this, I was not aware.

I never try to export the animations though so I wouldn't know if this is related to your configuration.
Last time I checked the animations were loading/playing fine on the 64 bit plugin.
If they do for you as well, I would rather contact Noesis's author. The plugin does not take care of the export, only of loading the animations. Noesis is taking care of the export. I know people have successfully exported animations for 2B using the 32 bit plugin, though they had to repack the dat several files in order to fit the 700 animation limit.

**Comment by keesoudwater34** [comment]
> Thanks for reporting this, I was not aware.
> 
> I never try to export the animations though so I wouldn't know if this is related to your configuration. Last time I checked the animations were loading/playing fine on the 64 bit plugin. If they do for you as well, I would rather contact Noesis's author. The plugin does not take care of the export, only of loading the animations. Noesis is taking care of the export. I know people have successfully exported animations for 2B using the 32 bit plugin, though they had to repack the dat several files in order to fit the 700 animation limit.

from memory if i recall correctly it didnt work before due to the ram limitation on noesis on 32 bit, not so much a hard animation limit? wierdly enough it does load everything at least im thinking it does since it pulls over 9 gigs at once. and then basically after a long while flushes that without exporting it. ill see if i can contact the noesis authur about it but imma keep this open for now and post in here when ive heard back.

**Comment by Kerilk** [comment]
I removed the hard coded limit when the 64 bit support was made available:
https://github.com/Kerilk/noesis_bayonetta_pc/commit/e7e5b7b74b75fa84a815d1de7f22734957c352b3
So your experience is indeed correct.

**Comment by keesoudwater34** [comment]
just did some more testing and yeh it does seem to be crapping out on export so it somehow is effected. the count for 2b's animation set seems to be around 814 animations in there. so just above it. ill be writing to noesis author in the morning. i was able to extract em when using the tools to seperate and repack to 2 seperate  packs. before i had to do many many more to get em out when testing it waayyyy back.

**Comment by keesoudwater34** [comment]
Kerilk just to confirm as you said. as soon as the 64 noesis was availible you removed the limiter? so in every 64 Bit Release that limiter is gone im assuming?

also i did hear back aswell from rich. he did say in FBX mode it was exporting fine the entire animation set. Am thinking it meight be a PSK PSA limit on noesis end but thats a guess at this moment.

To mention aswell as rich said " I know he’s removed it in his latest repository code as well, but you may be using a binary distribution that still has the limit in place. " its why im asking the first question since im assuming thats why he mentioned it. ill rerun it with the same version of the tool on fbx mode and see if it spits it out to see aswell.

----EDIT----
Can confirm it loading the fbx export compleetly did finish up. just waiting on one more reply from rich and if that has said in there what i think will be said ill close this down

**Comment by Kerilk** [comment]
The 64 bit plugin has the limit removed since the last 2 releases. The only way you could get an outdated one is if you were using the one that Rich is packaging himself. This one may be out of date depending on when Rich synced the sources.

**Comment by keesoudwater34** [comment]
got a reply back about the issue and i think its best if i quote rich with this " If FBX works and PSA doesn’t, you might be running into a PSA format limit on the frame count or something. Not in a position to check, but it wouldn’t be surprising, ActorX is pretty old and I do recall it generally being full of dumb limitations as a format." 

so basically due to limitiations in the format it would not go past its own designed limits. so at least now it explains why i wont export to PSA due to it. at least now if someone has this same issue and wonder why it at least explains why it doesnt spit it out. even with limits removed on the plugin itself it still does its own export limits as you said. it being a seperate system.

ill close down the issue right now but serieusly thank you for even awnsering my questions on this i really do appreciate it. and that goes for rich aswell when messaging him. thank you both.

**Comment by Kerilk** [comment]
You're welcome, glad you got to the bottom of it.
