### ISSUE TITLE
Babylon's Fall request 

### ISSUE THREAD

**Issue by DJNormality** [Kerilk/noesis_bayonetta_pc#31]
![ab0000-wmb-Fri-Mar-4-03-13-20-2022](https://user-images.githubusercontent.com/59482618/156875442-d8c76ac2-9b4b-4035-a2c1-44f778b81b61.png)

A quick look into these models to this game. Joschka pointed me here to maybe see if you could add support for it. I can post samples if you need.

**Comment by Kerilk** [comment]
I would be interested, please do.

**Comment by DJNormality** [comment]
Thank you so much here they are I threw in a bunch of random ones to test.

**Comment by Kerilk** [comment]
I would need whole dat and dtt files, ideally a whole cpk.

**Comment by DJNormality** [comment]
OK all I have are .pkz files. I have uploaded one here that's all I see.

**Comment by Kerilk** [comment]
It seems to work fine here. Here is what I get when I load em0001.dtt:
![Babylon's Fall](https://user-images.githubusercontent.com/1815142/156907531-e664fc1e-932e-4476-a33b-368d0a9abf0b.png)

**Comment by DJNormality** [comment]
Ok thank you maybe i just needed to update my version. 

*EDIT*
I must of done something to the files to get these .wmb files. Thank you again. I got it working now.

**Comment by Kerilk** [comment]
Awesome.

**Comment by DJNormality** [comment]
Wait. I notice PL.pkz has issues. Care to test a few please ?
![fiee](https://user-images.githubusercontent.com/59482618/156909723-93ac9e2e-5d16-49a7-91b9-efcbff48235d.png)

**Comment by Kerilk** [comment]
Most of those files only contain armatures and no models. I would need to fix the memory leak for when this happens, but for now consider this harmless. For now, the plugin will refuse to load models with no geometry. Rule of thumb, if the dtt is too small to contain a model, then it most probably doesn't.

The only suspicious one is pl00af, that seem to have strange animations, but those animations are really limited, so it could be an unused leftover model.

**Comment by DJNormality** [comment]
Ok thank you so much for helping me and for the amazing plugin. Still going strong 💯
