### ISSUE TITLE
Some .DAT files of MGRR couldn't be previewed

### ISSUE THREAD

**Issue by kalesuan** [Kerilk/noesis_bayonetta_pc#36]
![-e2884aa967c8b4](https://user-images.githubusercontent.com/58339184/197482068-f81f195e-efd2-4bc9-8995-b3c81e4464b3.png)
I tested all the .dat files of player and enemies,it seems only those of Riden and soldiers using single knives ,greatswords and hammers have this issue. It works well on DLC Sam ,DLC Blade Wolf and other enemies include bosses.
When I tried to extract those .dat files, it warned this way
![-54e27ed1245bc6d3](https://user-images.githubusercontent.com/58339184/197485139-b5ac7a7c-ede4-49d2-a9bb-25f5d4736756.png)
 That's all I know and thanks for your great work.

**Comment by Kerilk** [comment]
These dats, as far as I 've checked doe not contain a model.  pl000f.dat contains pl0010.eff, the special effects for the main player. pl000f.dtt is empty.

**Comment by kalesuan** [comment]
I just happened to find it out.
The animations file of Riden is in pl0010.dat.
Turn on animation prompt, open pl0100.dat change the specify prefix to pl0010, open pl0010.dat , the window will appear again, choose cancel.Then we can preview the animations.

**Comment by Komegatze** [comment]
> 

can you show the process of how you did this?
I'm trying that out based on your description but I must be doing something wrong

**Comment by Komegatze** [comment]
nvm I didnt read it right at first. thank you I've been trying to rip raidens anims for AGES.
