### ISSUE TITLE
Bayonetta 3 animation

### ISSUE THREAD

**Issue by redtankbai** [Kerilk/noesis_bayonetta_pc#38]
hi,

thanks for Bayonetta 3 update!

when dig into animation, i can load animations from pl00fd.dat and pl00ff.dat, but cannot get pl00fe.dat works
![image](https://user-images.githubusercontent.com/35935360/198925425-7674dd1f-c958-41f5-86c1-c58c87be4a82.png)

any idea? thanks

**Comment by Kerilk** [comment]
Those are motions for pl0010 (bayo 1 moveset most probably). Use the pl0010 prefix before loading pl00fe.dat.

**Comment by redtankbai** [comment]
ah ... yes, i start remember all the old tech i did with this tool
