### ISSUE TITLE
[bug]NieRAutomata The End of YoRHa Edition Texture 

### ISSUE THREAD

**Issue by Q4st** [Kerilk/noesis_bayonetta_pc#39]
The Uv of the texture is messed up！
![3](https://user-images.githubusercontent.com/58507193/200104029-db68bc30-7aa0-4bd8-8b9a-c46460577128.PNG)
![2](https://user-images.githubusercontent.com/58507193/200104032-c7a0da0a-cb07-4c92-935a-59c7cc7415e4.PNG)
![1](https://user-images.githubusercontent.com/58507193/200104037-23597198-40ee-43e9-97e3-b29bfda92fb9.PNG)

**Comment by Kerilk** [comment]
Thanks for reporting. I will check, but most probably an astc 6x6 texture decoded incorrectly. We don't know how to unswizzle them correctly yet. The UVs are fine. The same issue exists with Bayonetta 3.

**Comment by Kerilk** [comment]
Should be fixed in the latest release, thanks for reporting. If you find other problematic models, I'll update again.
