### ISSUE TITLE
missing translation on root bone

### ISSUE THREAD

**Issue by redtankbai** [Kerilk/noesis_bayonetta_pc#4]
hi,

after check the exported fbx animation, i notice there has no X and Z data on root bone's translation, only Y axis data has animation, which cause tone of foot sliding to character, so any idea to solve it?

cheers!

**Comment by Kerilk** [comment]
The character's movement are handled by the game and are not part of the animation.

**Comment by redtankbai** [comment]
no, it's not the character actor movement, it's the root bone movement
for example, my char not move just idle in spot and play idle breath animation, there should still has small translation on root bone( which is hips bone in this game ) come from the idle motion itself
but right now the result is X and Z animation is missing, which cause char foot will sliding on ground event with idle animation
in DMC anim tools they have similar issue initially, and then they fixed it with found extra translation data in mot file then create a root bone on ori point and applied that translation on it

**Comment by Kerilk** [comment]
You mean bone -1 which is the parent bone to the root bone. It indeed as horizontal animation information.
I'll come back to you later when I have more time.

**Comment by redtankbai** [comment]
yes, and they named it bone255 because -1 is not so beautiful, lol

**Comment by Kerilk** [comment]
Okay, try the new release and tell me if you spot something strange.

**Comment by redtankbai** [comment]
works perfect, many thanks!

**Comment by Kerilk** [comment]
Nice. Nonetheless I can't help thinking you are losing something by using the noesis plugin to export motions.

In the model some of the bones are animated by constraints (second hip joint and and second elbow joint bones for example), so creating new animations for the model will prove hard. Maybe it would be better if I could directly export the model to collada including constraints, and animations in their original format translated to collada (using interpolation).

**Comment by redtankbai** [comment]
i think those constraints are not hard to be reproduced in 3D software as long as we have all animated bone's transform, constraints usually driven leaf bone motion to provide better skin weight deformation.
sometimes they will use IK in engine, so you may see not motion on legs or arms, but if you can find the IK target bone they use to record animation, then everything can be reproduce again.

https://lukascone.wordpress.com/2017/06/18/mt-framework-tools/
