### ISSUE TITLE
can't find the .dll?

### ISSUE THREAD

**Issue by Komegatze** [Kerilk/noesis_bayonetta_pc#40]
I've been trying to figure this out for hours now. the I've extracted it about every way I can think of but I cannot find the dll file to replace in noesis. please help I am stuck.

**Comment by Kerilk** [comment]
It's in an archive in the release tab of the repository.
https://github.com/Kerilk/noesis_bayonetta_pc/releases/download/v0.9.49/bayonetta.7z
