### ISSUE TITLE
Editing .dat and .dtt files in the Astral Chain UI folder.

### ISSUE THREAD

**Issue by Digote** [Kerilk/noesis_bayonetta_pc#41]
Hi.
sorry for my bad english, is there any way to open the .dat or .dtt files from the Astral Chain UI folder, the other folders work perfectly, only the interface UI doesn't.

![image](https://user-images.githubusercontent.com/45742711/209821023-54bb24cb-101c-4ee8-bd24-cb6545b92ca5.png)

**Comment by Kerilk** [comment]
Usually, it means they do not contain models. It could be a bug, but given the game, it is unlikely.

**Comment by DiegoTegani** [comment]
Got it, must be another view and edit format for this type of file in this folder, thanks for the help.

**Comment by Digote** [comment]
Got it, must be another view and edit format for this type of file in this folder, thanks for the help.
