### ISSUE TITLE
Set up confusion, misunderstanding plug in adding steps

### ISSUE THREAD

**Issue by Galetron** [Kerilk/noesis_bayonetta_pc#47]
I'm confused over adding the plug in to the file, but I really need to get this plug in, hopefully Kerilk doesn't close this before I can get some help, but I am royally screwing up adding the plug in, the directions are confusing me, so having help giving very blunt and clear guiding, exact file locations and names would help greatly.

**Comment by Kerilk** [comment]
Thanks for your interest. I rewrote the instructions, tell me if they make sense now.

**Comment by Galetron** [comment]
thanks! after messing with it a bit more with the new instructions, I was able to get it to work, hopefully this helps new people to the noesis bayonetta mod, because it did help me
