### ISSUE TITLE
Astral Chain Texture Replacement

### ISSUE THREAD

**Issue by SilentStorm-1986** [Kerilk/noesis_bayonetta_pc#49]
Hi, thanks for your work on these scripts. I've been trying to mod textures for Astral Chain, but the textures are not showing up in game. I think this is because either the DAT files or WTA files contain hashes for the files, unless I'm doing something wrong. Is the hash table for the DAT supposed to be recalculated when the files are are reassembled or will this basically be reinserted without changes? I'm thinking maybe this was never solved because there's no real mods for this game.

**Comment by Kerilk** [comment]
I don't know what scripts you are referencing (maybe the bayonetta tools) but yes if you want to swap textures, you need to have them replace existing one, keeping the hash. If you add the textures, they'll be assigned a new hash and the hash will need to be updated in materials that use the original texture.

**Comment by SilentStorm-1986** [comment]
> I don't know what scripts you are referencing (maybe the bayonetta tools) but yes if you want to swap textures, you need to have them replace existing one, keeping the hash. If you add the textures, they'll be assigned a new hash and the hash will need to be updated in materials that use the original texture.

Yes, I meant bayonetta tools, didn't mean to post this issue in this repo.

Do you know what happens if the texture resolution is changed? I could not figure that out... I kept thinking it had something to do with the hash needing to be recalculated.
