### ISSUE TITLE
Neosis Crash When Export Anim

### ISSUE THREAD

**Issue by redtankbai** [Kerilk/noesis_bayonetta_pc#5]
https://i.imgur.com/rT5Pa3i.png

it's only happen on Main character of Neir
mesh file = pl0000.dtt
anim file = pl000f.dat
anim perfix = pl0000
char can be preview with animation in Neosis, but will crash when export char with anim, i tried export fbx, psa and they all crash
also tried export from preview, and crash as well

all other char of that game working well, seems like it's too many anim data may cause out of memory (i do have enough physical memory)

thanks!

**Comment by Kerilk** [comment]
Noesis is limited to 4GB of ram. I limit Nier anime to the first 700 animations else Noesis would run out of memory when viewing 2B animations.

The best thing you can do is unpack the dat file containing the animations and repack it with only part of the animations.

You can find several alternatives to unpack/repack platinum dat files.

**Comment by redtankbai** [comment]
yes, you are right, reduce mot count and repack works well

thanks!

**Comment by quang23021998** [comment]
Sir, may I ask how did you unpack and repack the dat file?
