### ISSUE TITLE
Neosis crashes on nier weapon file

### ISSUE THREAD

**Issue by redtankbai** [Kerilk/noesis_bayonetta_pc#6]
these three crashes:
wpf000.dtt
wpf200.dtt
wpf400.dtt
this one works
wpf600.dtt

i cannot get correct combat anim without weapon motion for NieR

Thanks!

**Comment by Kerilk** [comment]
Certainly a side effect of what I had to do to enable parent bone motion, as they used to be working (thought animations may have been wrong on those). Unfortunately I have to be moving for 6 month, and I may very well be unable to update the code for this period.

Sorry about that.

**Comment by redtankbai** [comment]
i tried initial support nier version, but same result on crash, even with no root motion
https://github.com/Kerilk/noesis_bayonetta_pc/releases/tag/0.9.16

if you know which version can load those anim without crash, plz tell me, root motion can be ignore on them

thanks!

**Comment by Kerilk** [comment]
I don't know, and I can't try them before a long time. Just try them all starting from the most recent.

**Comment by redtankbai** [comment]
after a couple tried, actually the latest build crashes on one machine but works on another machine with same setting, idk how that happen but anyway i got weapon anims i need, thx!

**Comment by Kerilk** [comment]
Weapons don't crash anymore but they don't have a bone defined. Thus the animations are not working. I'll look into it.

**Comment by Kerilk** [comment]
Should be fixed in https://github.com/Kerilk/noesis_bayonetta_pc/releases/tag/v0.9.25
Update Noesis to the latest version.
Please tell me if I missed some.

**Comment by xiangxiangjiang** [comment]
Thanks QAQ
