### ISSUE TITLE
HI，I can't find the animated files of the Bayonetta 2 protagonists.Please help me.

### ISSUE THREAD

**Issue by kong1313113** [Kerilk/noesis_bayonetta_pc#7]
In addition,when I tried to export the animation of the Nier automata protagonists, the software crashed.Do you have a solution?

**Comment by Kerilk** [comment]
Sorry I don't have more time, but those two questions have been answered already:

https://github.com/Kerilk/noesis_bayonetta_pc/issues/5
https://github.com/Kerilk/noesis_bayonetta_pc/issues/3
