### ISSUE TITLE
Metal Gear Rising support

### ISSUE THREAD

**Issue by redtankbai** [Kerilk/noesis_bayonetta_pc#8]
Hi,
is that possible to support metal gear rising?
it's made by same studio of bayonetta and file format is same "dtt", "dat"

i tried open with current plugin, but not working.

here is sample files:
https://drive.google.com/open?id=11hTtiCo9gvmKokzAXdKaigavyrgdIqkQ

Thanks!

**Comment by Kerilk** [comment]
It is on the todo-list, at least for geometry. The format is quite different as, if I remember well, it uses Havok for animations. So animation support might be out of the question for now.

**Comment by redtankbai** [comment]
if it's havok, could you manage export them as hkx that i can try lucky with some other tools?

**Comment by Kerilk** [comment]
In fact it uses the same animation system as Bayonetta 2, and the levels are quite similar.

So I added support for MGRR. Animations and level are working. For now shadow meshes are ignored. Materials are not top notch, but it will suffice for now.

Tell me if you find blocking issues.

**Comment by redtankbai** [comment]
Great thanks! Will try and let you know asap!

**Comment by Kerilk** [comment]
The motion files for the main character are in pl0010.dat. Use the pl0010 prefix if you want to load them, as there are no models in this file.

**Comment by redtankbai** [comment]
everything looks good, thx!

**Comment by Kerilk** [comment]
Thanks for the report!

**Comment by Li-ZhuoHang** [comment]
> 主角的运动文件在 pl0010.dat。如果要加载它们，请使用 pl0010 前缀，因为此文件中没有模型。

I don't seem to see the animation of the stick or whip of the main character. Do you know where it is?

**Comment by Kerilk** [comment]
Many weapon related animations are in the weapon's files.

**Comment by Li-ZhuoHang** [comment]
> Many weapon related animations are in the weapon's files.
I mean, the main character holds the animation of stick or whip. Is it in the weapon file?

**Comment by Kerilk** [comment]
Yes, the plugin should prompt you to open other files to load extra animations. If it doesn't, activate the option in the Bayonetta entry of the tools menue.

**Comment by Li-ZhuoHang** [comment]
Is this the way to operate? There seems to be an error.
https://drive.google.com/file/d/1-DlHKVjsFicnTrfK9cuPAA8iAM62qX-v/view?usp=sharing

**Comment by Kerilk** [comment]
You're almost good, but when you changed the prefix you wrote wp2000 whereas you should have written pl0010, and then loaded wp2000.dat

pl0010 is the prefix of the main character animations

**Comment by Li-ZhuoHang** [comment]
> You're almost good, but when you changed the prefix you wrote wp2000 whereas you should have written pl0010, and then loaded wp2000.dat
> 
> pl0010 is the prefix of the main character animations

Thank you very much. I have successfully extracted the animation. May I ask why this is the case?

**Comment by Kerilk** [comment]
just that pl0010 is hard coded in the engine as the main playable character (it is Bayonetta's playable character model number as well). All animations that pertain to this the main playable are prefixed with pl0010. When you wrote wp2000 as a prefix you applied the whip animations to the player armature. I hope this helps.

**Comment by Li-ZhuoHang** [comment]
> just that pl0010 is hard coded in the engine as the main playable character (it is Bayonetta's playable character model number as well). All animations that pertain to this the main playable are prefixed with pl0010. When you wrote wp2000 as a prefix you applied the whip animations to the player armature. I hope this helps.

Thank you for your answer
