### ISSUE TITLE
unsuccessful searching repack platinum dat files.

### ISSUE THREAD

**Issue by Skykila** [Kerilk/noesis_bayonetta_pc#9]
I can't find repack platinum dat files. Pleace help.

**Comment by Kerilk** [comment]
The tools to unpack and repack platinum files are in the https://github.com/Kerilk/bayonetta_tools repository. they are ruby scripts, namely dat_extractor.rb and dat_creator.rb

There are a number of gems you need to install to get those working, they are given in the README
You must download/clone the whole bayonetta_tools repository, as the tools are not self contained.

If you have issues, please continue the discussion in the other repository tracker.

Thanks for the interest.

**Comment by Skykila** [comment]
thank you very much!

**Comment by xiangxiangjiang** [comment]
I want to split animation file(pl001f.dat) into some files ,but I don't know how to select platinum dat files to repack without problems. Thank you
![image](https://user-images.githubusercontent.com/34119248/59511785-c2e7b500-8ee9-11e9-9577-6057206f41a8.png)
![image](https://user-images.githubusercontent.com/34119248/59511824-df83ed00-8ee9-11e9-8f3c-be507b543736.png)

**Comment by Kerilk** [comment]
I you want to remove some files and then repack the dat file, you just want to edit the ```.metadata/layout.yaml``` file. Just delete the lines you don't want. Files not in the layout.yaml file are ignored.

**Comment by xiangxiangjiang** [comment]
Thank you! you help me a lot

**Comment by xiangxiangjiang** [comment]
Excuse me. Thanks a lot for your tools.I have a question. When I unpack the pl000f.dat file,I get a pl0000AtkCombo.csv file. Could you tell me what meaning of those rows and columns are?
![image](https://user-images.githubusercontent.com/34119248/62096957-0fc7f500-b2b8-11e9-80a5-de76f1757a99.png)

**Comment by Kerilk** [comment]
I would say the description of the combos of enemy bayo in witch trial 5 chapter 11
